# Generated by Django 4.2.2 on 2023-07-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_categorytest_alter_task_datecompleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xtorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='example')),
            ],
        ),
    ]
