# Generated by Django 4.2.2 on 2023-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_groupmembers_groupusers_delete_taskgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='invite_reason',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
