# Generated by Django 4.2.2 on 2023-07-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='invite_reason',
            new_name='charge',
        ),
    ]
